baseURL                 = 'https://wecamp.pro/'
canonifyurls            = "true"
languageCode            = 'fa-ir'
title                   = 'وی‌کمپ، کمپ‌های حرفه‌ای'
publishDir              = "docs"

[permalinks]
    about-us             = "/:section/:filename/"  #why :filename, why not :title? not to break the return link in shop page; Better to use another idea by coding a bit in future.
    blog                = "/:section/:year/:month/:title/"
    apply                 = "/:section/:filename/"
    something_else                = "/:title/"

[[cascade]]
   [cascade._target]
    path = '/camps/cloud-hunterss'
    [cascade.params]
      layout = "cloud-hunters"
[[cascade]]
   [cascade._target]
    path = '/camps/cloud-architects'
    [cascade.params]
      layout = "cloud-architects"
[[cascade]]
   [cascade._target]
    path = '/camps/design-magic'
    [cascade.params]
      layout = "design-magic"
[[cascade]]
   [cascade._target]
    path = '/camps/devops-taste'
    [cascade.params]
      layout = "devops-taste"

[[cascade]]
   [cascade._target]
    path = '/camps/price'
    [cascade.params]
      layout = "price"
