baseURL                 = 'https://wecamp.pro/'
canonifyurls            = "true"
languageCode            = 'fa-ir'
title                   = 'وی‌کمپ، کمپ‌های حرفه‌ای'
publishDir              = "docs"

[permalinks]
    about-us             = "/:section/:filename/"  #why :filename, why not :title? not to break the return link in shop page; Better to use another idea by coding a bit in future.
    blog                = "/:section/:year/:month/:title/"
    apply                 = "/:section/:filename/"
    something_else                = "/:title/"

[[cascade]]
   [cascade._target]
    path = '/camps/cloud-hunters'
    [cascade.params]
      layout = "cloud-hunters"
